---
- name: Deploy Container Hosts
  become: true
  hosts: container_hosts
  roles:

#Installs Homebrew
    - { role: homebrew, become: false }

#TODO: Deploy docker with Brew.  Using apt for now. 
    - { role: docker }

#Future Role
    - { role: lxc}



